// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_dnDRTCeOtzgJlvC75nwXMmfAsA1Hu9g',
    appId: '1:225751816843:web:8d62599d5310e44a4a928e',
    messagingSenderId: '225751816843',
    projectId: 'music-app-976f8',
    authDomain: 'music-app-976f8.firebaseapp.com',
    storageBucket: 'music-app-976f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmE_UcHFaKfI7hgRFVdJm1l9oXLGBudbw',
    appId: '1:225751816843:android:c9227f62cfd2305b4a928e',
    messagingSenderId: '225751816843',
    projectId: 'music-app-976f8',
    storageBucket: 'music-app-976f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyLtCxnv2T5_uiCDNU4tvay3eQgQSezYQ',
    appId: '1:225751816843:ios:4ae23097bec38a824a928e',
    messagingSenderId: '225751816843',
    projectId: 'music-app-976f8',
    storageBucket: 'music-app-976f8.appspot.com',
    iosBundleId: 'com.example.musicPlayerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyLtCxnv2T5_uiCDNU4tvay3eQgQSezYQ',
    appId: '1:225751816843:ios:4ae23097bec38a824a928e',
    messagingSenderId: '225751816843',
    projectId: 'music-app-976f8',
    storageBucket: 'music-app-976f8.appspot.com',
    iosBundleId: 'com.example.musicPlayerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_dnDRTCeOtzgJlvC75nwXMmfAsA1Hu9g',
    appId: '1:225751816843:web:4c90d43f2b5f0a4f4a928e',
    messagingSenderId: '225751816843',
    projectId: 'music-app-976f8',
    authDomain: 'music-app-976f8.firebaseapp.com',
    storageBucket: 'music-app-976f8.appspot.com',
  );
}
